{
    const myCharlist = `
aces-high-eddie-gunner
alexander-eddie-warrior
alliance-general-sentinel
allied-bomber-boy-magus
allied-bomber-boy-sentinel
allied-soldier-magus
allied-soldier-sentinel
allied-soldier-warrior
angel-eddie-gunner
angel-of-fear-warrior
angel-of-mercy-gunner
angel-of-pain-magus
angel-of-strife-sentinel
anubis-assassin
anubis-gunner
anubis-sentinel
anubis-warrior
apma-robo-scout-warrior
artillery-dog-assassin
astra-valkyrie-slayer-assassin
axis-bomber-boy-assassin
axis-bomber-boy-warrior
axis-soldier-assassin
axis-soldier-magus
banshee-gunner
banshee-magus
banshee-sentinel
bastion-sentinel
battlefield-trooper-eddie-warrior
beast-eddie-assassin
benjamin-breeg-eddie-sentinel
blackbeard-eddie-gunner
burning-mummy-dog-assassin
caria-woman-in-uniform-gunner
carriage-rider-eddie-magus
child-of-the-damned-gunner
child-of-the-damned-magus
child-of-the-damned-warrior
chopper-assassin
chopper-magus
chopper-sentinel
clansman-eddie-warrior
convict-gunner
convict-magus
corrupt-droid-assassin
corrupt-droid-magus
corrupt-droid-sentinel
corrupt-droid-warrior
corrupt-harpy-assassin
corrupt-owl-cultist-magus
corrupt-ox-cultist-assassin
corrupt-ox-cultist-sentinel
corrupt-rescuer-assassin
corrupt-rescuer-gunner
corrupt-rescuer-magus
corrupt-rescuer-sentinel
corrupt-rescuer-warrior
cosmic-golden-son-gunner
cosmic-lord-of-light-gunner
cosmic-odin-magus
crimean-soldier-magus
crimean-soldier-sentinel
crimson-pharaoh-dog-warrior
crusader-eddie-magus
cultist-warden-warrior
cursed-pharaoh-dog-assassin
cyborg-eddie-gunner
daedalus-warrior
damned-templar-knight-warrior
death-dog-assassin
death-dog-warrior
demon-dog-warrior
demon-officer-magus
demon-spawn-assassin
demon-spawn-gunner
demon-spawn-magus
demon-spawn-sentinel
demon-spawn-warrior
derby-demon-assassin
derby-demon-gunner
derby-demon-sentinel
derby-demon-warrior
desert-golem-gunner
desert-guardian-sentinel
desert-marauder-gunner
desert-rider-assassin
desert-sniper-assassin
dog-of-war-sentinel
domino-woman-in-uniform-magus
doomsday-eddie-gunner
eda-valkyrie-knight-gunner
eddie-warrior
edward-the-great-magus
empress-mother-russia-assassin
eternity-eddie-assassin
executioner-eddie-assassin
fallen-icarus-eddie-gunner
fear-of-the-dark-eddie-sentinel
final-frontier-eddie-sentinel
flight-of-icarus-eddie-gunner
football-eddie-chile-warrior
football-eddie-west-ham-assassin
ghost-of-the-navigator-sentinel
golden-pharaoh-dog-gunner
golden-son-assassin
golden-son-gunner
golden-son-magus
golden-son-sentinel
golden-son-warrior
grim-reaper-eddie-magus
gunner-dog-gunner
gunnr-valhalla-maiden-gunner
hallowed-eddie-gunner
harpy-sentinel
harpy-warrior
haunted-pumpkin-gunner
haunted-pumpkin-magus
hellhound-assassin
hellhound-warrior
hellraiser-gunner
hellraiser-magus
hellraiser-sentinel
hellraiser-warrior
hierophant-assassin
hierophant-sentinel
hierophant-warrior
horus-sentinel
ibuki-shinobi-ranger-gunner
icarus-sentinel
ichiyou-shinobi-medic-sentinel
ingami-dog-spirit-sentinel
inugami-dog-spirit-magus
iron-eddie-assassin
kari-valkyrie-siren-magus
khan-eddie-warrior
killers-eddie-assassin
koku-shinobi-bandit-assassin
kurenai-shinobi-rogue-warrior
lady-azov-magus
lamia-reaper-boss-assassin
lilith-assassin
lilith-gunner
lilith-magus
lilith-sentinel
lilith-warrior
lord-of-light-sentinel
lord-of-light-warrior
maclo-robo-scout-sentinel
masked-harpy-magus
mayan-priestess-gunner
mayan-priestess-magus
mayan-priestess-sentinel
mayan-priestess-warrior
minazuki-shinobi-spy-magus
minotaur-assassin
minotaur-magus
minotaur-sentinel
minotaur-warrior
mongol-archer-magus
mummy-eddie-sentinel
mystic-eddie-magus
navigator-eddie-gunner
newborn-of-light-assassin
newborn-of-light-gunner
newborn-of-light-magus
newborn-of-light-sentinel
newborn-of-light-warrior
onyx-son-gunner
onyx-son-warrior
phantom-eddie-warrior
pharaoh-dog-king-assassin
pharaoh-dog-king-gunner
pharaoh-dog-magus
pharaoh-eddie-sentinel
piece-of-mind-eddie-sentinel
pirate-skeleton-sentinel
plague-doctor-harpy-gunner
possessed-rockets-gunner
possessed-rockets-warrior
possessed-snowman-magus
prison-cook-assassin
procyon-cosmic-wolf-gunner
pyro-soldier-assassin
pyro-soldier-magus
pyro-soldier-sentinel
pyro-soldier-warrior
queens-guard-warrior
ragna-valkyrie-hunter-warrior
raven-witch-assassin
rock-golem-sentinel
rocket-dog-warrior
rota-valhalla-maiden-magus
run-to-the-hills-eddie-warrior
sacro-robo-scout-magus
samurai-eddie-warrior
sanctified-templar-knight-gunner
savage-reaper-sentinel
savage-reaper-warrior
scream-for-me-eddie-sentinel
seventh-son-eddie-magus
shadow-wicker-man-eddie-magus
shaman-eddie-warrior
shardborne-assassin
shardborne-gunner
shardborne-magus
shardborne-sentinel
shardborne-warrior
slaughtered-daughter-warrior
sojobo-tengu-king-sentinel
soldier-eddie-gunner
soulless-demon-assassin
soulless-demon-magus
soulless-demon-sentinel
soulless-demon-warrior
speed-of-light-eddie-magus
storm-eddie-assassin
strong-sacrificial-heart-warrior
tarobo-tengu-warden-gunner
the-alchemist-magus
the-ancient-mariner-magus
the-beast-assassin
the-cannoneer-gunner
the-clairvoyant-magus
the-count-dracula-warrior
the-edless-horseman-gunner
the-killer-beast-warrior
the-killer-prime-sentinel
the-madam-magus
the-nomad-warrior
the-prisoner-gunner
the-wicker-man-warrior
the-witch-doctor-sentinel
thelxiepia-siren-corsair-warrior
thor-eddie-warrior
trickster-assassin
trickster-magus
trickster-sentinel
trickster-warrior
trjegul-the-skogkatt-magus
troll-assassin
troll-sentinel
troll-warrior
trooper-eddie-warrior
ultimate-sacrificial-heart-warrior
undead-allied-soldier-gunner
undead-allied-soldier-sentinel
undead-axis-gunner-assassin
undead-axis-gunner-warrior
undead-convict-sentinel
undead-crimean-soldier-assassin
undead-rescuer-assassin
undead-rescuer-gunner
undead-rescuer-magus
undead-rescuer-sentinel
undead-rescuer-warrior
val-valkyrie-guardian-sentinel
vampire-hunter-eddie-assassin
van-helsing-eddie-assassin
viking-invader-eddie-sentinel
virtual-xi-eddie-sentinel
virus-eddie-warrior
visions-eddie-sentinel
war-golem-assassin
war-golem-magus
war-golem-warrior
warlord-assassin
werewolf-assassin
werewolf-gunner
werewolf-magus
werewolf-sentinel
where-eagles-dare-eddie-assassin
wicker-golem-assassin
wicker-man-eddie-magus
wicker-owl-cultist-magus
wicker-owl-evolved-magus
wicker-ox-cultist-sentinel
wicker-wolf-cultist-warrior
wicker-wolf-evolved-warrior
wickerdog-king-warrior
wickerdog-queen-magus
wrath-assassin
x-factor-eddie-magus
`.split('\n')

const charList = Array.from(document.querySelectorAll('.ch-icon a')).filter(a => {
    const id = a.href.split('/').reverse()[1]
    return myCharlist.includes(id)
})

charList.forEach(a => a.parentElement.style.opacity = 0.2)
}